apiVersion: v1
kind: Pod
metadata:
  name: web-terminal-test
spec:
  containers:
  - name: web-terminal
    image: projectgreenist/web-terminal:0.1.1
    imagePullPolicy: Always
    command: ["sleep", "infinity"]
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi