# =================================================================
# 1. 역할 정의 (ClusterRole)
# =================================================================
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer-role
rules:
- apiGroups: [ "", "apps", "extensions", "networking.k8s.io" ]
  resources: [ "pods", "services", "deployments", "ingresses", "configmaps" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-role
rules:
- apiGroups: [ "", "apps", "extensions", "networking.k8s.io" ]
  resources: [ "pods", "services", "deployments", "ingresses", "configmaps", "secrets" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups: [ "" ]
  resources: [ "pods/log" ]
  verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaced-admin-role
rules:
- apiGroups: [ "*" ]
  resources: [ "*" ]
  verbs: [ "*" ]

# =================================================================
# 2. 클러스터 전체 권한 부여 (ClusterRoleBinding)
# =================================================================
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins-binding
subjects:
- kind: Group
  name: cluster-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

# =================================================================
# 3. 'blue' 네임스페이스 권한 부여 (RoleBinding)
# =================================================================
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-admins-binding
  namespace: blue
subjects:
- kind: Group
  name: blue-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespaced-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-developers-binding
  namespace: blue
subjects:
- kind: Group
  name: blue-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-viewers-binding
  namespace: blue
subjects:
- kind: Group
  name: blue-viewers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io

# =================================================================
# 4. 'red' 네임스페이스 권한 부여 (RoleBinding)
# =================================================================
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: red-admins-binding
  namespace: red
subjects:
- kind: Group
  name: red-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespaced-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: red-developers-binding
  namespace: red
subjects:
- kind: Group
  name: red-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: red-viewers-binding
  namespace: red
subjects:
- kind: Group
  name: red-viewers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io

# =================================================================
# 5. 'fdc' 네임스페이스 권한 부여 (RoleBinding)
# =================================================================
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdc-admins-binding
  namespace: fdc
subjects:
- kind: Group
  name: /thadoop/fdc/adm
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespaced-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdc-developers-binding
  namespace: fdc
subjects:
- kind: Group
  name: /thadoop/fdc/dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdc-viewers-binding
  namespace: fdc
subjects:
- kind: Group
  name: /thadoop/fdc/view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io
